CONFIG_NAME: interop
PRESET_BASE: interop

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0

# Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 16

# Deneb
DENEB_FORK_VERSION: 0x20000093
DENEB_FORK_EPOCH: 0

# Time parameters
SECONDS_PER_SLOT: 5
SLOTS_PER_EPOCH: 2

SECONDS_PER_ETH1_BLOCK: 5

#config deposit->active faster
EPOCHS_PER_ETH1_VOTING_PERIOD: 1
ETH1_FOLLOW_DISTANCE: 1

# Config pending->exit fastẻ 
SHARD_COMMITTEE_PERIOD: 1

# Config coinbase to become validator
# MAX_EFFECTIVE_BALANCE: 16000000000

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
